# Generated by Django 6.1.1 on 2026-09-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('codigo_carro', models.CharField(max_length=50)),
                ('nombre_auditor', models.CharField(max_length=150)),
                ('responsable_carro_auditado', models.CharField(max_length=150)),
                ('supervisor_responsable', models.CharField(default='Juanito Arias', max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('estado_dictamen', models.CharField(max_length=100)),
                ('total_verificadas', models.IntegerField(default=0)),
                ('total_herramientas', models.IntegerField(default=0)),
                ('detalles_faltantes', models.TextField(blank=True, default='')),
                ('comentarios_auditor', models.TextField(blank=True, default='')),
                ('firma_auditor_base64', models.TextField(blank=True, null=True)),
                ('firma_responsable_base64', models.TextField(blank=True, null=True)),
                ('ldap_auditor_id', models.CharField(blank=True, default='', max_length=50)),
                ('ldap_responsable_id', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspección 5S',
                'verbose_name_plural': 'Inspecciones 5S',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='ToolCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_carro', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre_carro', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('TURNO', 'Turno Operativo'), ('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico / Instrumentación'), ('MECATRONICO', 'Mecatrónico / Automatización')], default='TURNO', max_length=50)),
                ('especialidad_tipo', models.CharField(blank=True, default='', max_length=150)),
                ('area', models.CharField(default='Planta Goodyear', max_length=150)),
                ('ubicacion_especifica', models.CharField(blank=True, default='Bahía de Mantenimiento', max_length=200)),
                ('foto_ubicacion_url', models.TextField(blank=True, null=True)),
                ('fotos_gavetas_json', models.TextField(blank=True, default='{}')),
                ('supervisor_responsable', models.CharField(default='Juanito Arias', max_length=150)),
                ('total_herramientas', models.IntegerField(default=0)),
                ('estado_general', models.CharField(default='OK', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carro de Herramientas',
                'verbose_name_plural': 'Carros de Herramientas',
                'ordering': ['codigo_carro'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMissingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gaveta', models.IntegerField()),
                ('nombre_herramienta_faltante', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_items', to='inspections.inspection5s')),
            ],
            options={
                'verbose_name': 'Detalle de Faltante',
                'verbose_name_plural': 'Detalles de Faltantes',
            },
        ),
        migrations.AddField(
            model_name='inspection5s',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.toolcart'),
        ),
        migrations.CreateModel(
            name='DrawerTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gaveta', models.IntegerField(choices=[(1, 'Gaveta 1'), (2, 'Gaveta 2'), (3, 'Gaveta 3'), (4, 'Gaveta 4'), (5, 'Gaveta 5')])),
                ('nombre_herramienta', models.CharField(max_length=200)),
                ('orden_posicion', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='inspections.toolcart')),
            ],
            options={
                'verbose_name': 'Herramienta de Gaveta',
                'verbose_name_plural': 'Herramientas de Gavetas',
                'ordering': ['numero_gaveta', 'orden_posicion', 'id'],
            },
        ),
    ]
