# Generated by Django 6.1.1 on 2026-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection5s',
            name='codigo_carro',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection5s',
            name='fecha_inspeccion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='drawertool',
            index=models.Index(fields=['cart', 'numero_gaveta'], name='inspections_cart_id_f7e9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection5s',
            index=models.Index(fields=['codigo_carro', '-fecha_inspeccion'], name='inspections_codigo__411b66_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionmissingitem',
            index=models.Index(fields=['inspection', 'numero_gaveta'], name='inspections_inspect_0154f5_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcart',
            index=models.Index(fields=['categoria'], name='inspections_categor_1d8141_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcart',
            index=models.Index(fields=['area'], name='inspections_area_795b57_idx'),
        ),
    ]
